### ISSUE TITLE
no route found for GET /users/log_in (ExampleWeb.Router)

### ISSUE THREAD

**Issue by sfusato** [BartOtten/routex_example#1]
The route exists though: `mix phx.routes | grep "users/log_in"`

```elixir
user_session_path  POST    /users/log_in                                             ExampleWeb.UserSessionController :create
user_session_europe_path  POST    /europe/users/log_in                                      ExampleWeb.UserSessionController :create
user_session_gb_path  POST    /gb/users/log_in                                          ExampleWeb.UserSessionController :create
```

**Comment by sfusato** [comment]
Actually, it doesn't. Only now I've seen that it's the `POST` method coming from `post "/users/log_in", UserSessionController, :create`.

For some reason, `live "/users/log_in", UserLoginLive, :new` is ignored, wasn't processed.

**Comment by BartOtten** [comment]
Sorry for the delay; can confirm the route was swallowed and published a fix.

Thanks for taking time to take Routex for a test drive
